version: "3.8"

services:
  app:
    container_name: my-app
    image: my-app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - 4000:${PORT}
    env_file:
      - .env